# Generated by Django 5.1.15 on 2026-07-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0002_alter_licenseassignment_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="licenseassignment",
            name="asset",
        ),
    ]
