# Generated by Django 5.1.15 on 2026-06-29 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('employees', '0004_remove_employee_idx_emp_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.tenantuser'),
        ),
    ]
