# Generated by Django 5.1.15 on 2026-07-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_incident_created_by_alter_incident_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='ai_category',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='ai_confidence',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='ai_model_version',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='ai_summary',
        ),
    ]
